# Generated by Django 2.2 on 2019-05-10 03:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='name')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 3, 38, 19, 318053), verbose_name='date created')),
                ('editedAt', models.DateTimeField(null=True, verbose_name='date edited')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateTimeField()),
                ('End', models.DateTimeField(verbose_name='end_time')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 3, 38, 19, 318666), verbose_name='date created')),
                ('editedAt', models.DateTimeField(null=True, verbose_name='date edited')),
                ('notesToGuide', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=500, verbose_name='description')),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 10, 3, 38, 19, 319279), verbose_name='date created')),
                ('editedAt', models.DateTimeField(null=True, verbose_name='date edited')),
                ('Tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tours', unique=True)),
            ],
        ),
    ]
