# Generated by Django 2.2 on 2019-05-14 14:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('country_code', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=22, verbose_name='name')),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 561587), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250, verbose_name='description')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 562586), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=500, verbose_name='description')),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 567586), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitors', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start', models.DateTimeField(verbose_name='start_time')),
                ('End', models.DateTimeField(verbose_name='end_time')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 563586), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('notesToGuide', models.CharField(max_length=500, null=True, verbose_name='description')),
                ('Guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitors')),
                ('Guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('state_code', models.CharField(max_length=5, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Countries')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('content', models.TextField()),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 564586), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('Guide', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Guide')),
                ('creator', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 14, 7, 32, 55, 568586), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guide', unique=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitors', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('city_code', models.CharField(max_length=5, null=True)),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.States')),
            ],
        ),
    ]
