# Generated by Django 2.2 on 2019-05-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourtype',
            name='name',
            field=models.CharField(choices=[('General', 'General'), ('Food', 'Food'), ('Adventure', 'Adventure'), ('Shopping', 'Shopping'), ('Educational', 'Educational'), ('Mixed', 'Mixed')], max_length=50, unique=True),
        ),
    ]
