# Generated by Django 2.2 on 2019-05-14 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 152696), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 147698), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 148697), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 147698), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 151696), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 20, 57, 1, 150696), verbose_name='date created'),
        ),
    ]
