# Generated by Django 2.2 on 2019-05-13 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 387142), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 382109), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 384109), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='Start',
            field=models.DateTimeField(verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 383114), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 387142), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 17, 28, 9, 386143), verbose_name='date created'),
        ),
    ]
