# Generated by Django 2.2 on 2019-05-14 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190513_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='name',
            field=models.CharField(default='default', max_length=22, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='disputes',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 25930), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 18931), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 20930), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 19932), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 24932), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 14, 33, 22929), verbose_name='date created'),
        ),
    ]
