# Generated by Django 2.2 on 2019-05-14 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190514_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tour')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitor')),
            ],
        ),
    ]
