# Generated by Django 2.2 on 2019-06-01 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190530_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitor'),
        ),
        migrations.DeleteModel(
            name='Visitors',
        ),
    ]
