# Generated by Django 2.2 on 2019-06-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190601_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='title',
            field=models.CharField(blank=True, default='Tour', max_length=50),
        ),
    ]
