# Generated by Django 2.2 on 2019-05-11 18:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190510_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 11, 42, 104814), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 11, 42, 105812), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 11, 42, 105812), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 11, 42, 108847), verbose_name='date created'),
        ),
        migrations.CreateModel(
            name='VisitorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=500, verbose_name='description')),
                ('stars', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 11, 11, 11, 42, 109816), verbose_name='date created')),
                ('editedAt', models.DateTimeField(null=True, verbose_name='date edited')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitors', unique=True)),
            ],
        ),
    ]
