# Generated by Django 2.2 on 2019-05-11 18:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_auto_20190510_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Tour',
        ),
        migrations.AddField(
            model_name='review',
            name='Guide',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Guide'),
        ),
        migrations.AddField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 51, 50, 480407), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 51, 50, 481584), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 51, 50, 480970), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 11, 18, 51, 50, 483271), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
