# Generated by Django 2.2 on 2019-05-14 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190513_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='name',
        ),
        migrations.AlterField(
            model_name='disputes',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 953010), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 946010), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 948014), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 947012), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 952010), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 8, 951010), verbose_name='date created'),
        ),
    ]
