# Generated by Django 2.2 on 2019-05-14 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190513_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputes',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 684463), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 679462), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 681463), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 680459), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 684463), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 13, 21, 40, 19, 682462), verbose_name='date created'),
        ),
    ]
