# Generated by Django 2.2 on 2019-06-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190604_0142'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='TourRequest',
        ),
    ]
