# Generated by Django 2.2 on 2019-06-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190604_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Guide'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Visitor'),
        ),
    ]
