# Generated by Django 2.2 on 2019-05-12 03:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190512_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 3, 12, 5, 413316), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 3, 12, 5, 414512), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 3, 12, 5, 413895), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 3, 12, 5, 416194), verbose_name='date created'),
        ),
    ]
