# Generated by Django 2.2 on 2019-05-12 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190511_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitors',
            name='name',
        ),
        migrations.AlterField(
            model_name='guide',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 609075), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='editedAt',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 611073), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='review',
            name='editedAt',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tours',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 610073), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='tours',
            name='editedAt',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 615075), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitorreview',
            name='editedAt',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitors',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 613074), verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='visitors',
            name='editedAt',
            field=models.DateTimeField(auto_now=True, default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Disputes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2019, 5, 12, 9, 25, 11, 616073), verbose_name='date created')),
                ('editedAt', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Guide', unique=True)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Visitors', unique=True)),
            ],
        ),
    ]
